.nh
.TH "DOCKER" "1" "Jan 2020" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker - A self-sufficient runtime for containers


.SH SYNOPSIS
.PP
\fBdocker [OPTIONS] COMMAND [ARG...]\fP


.SH DESCRIPTION
.PP
A self-sufficient runtime for containers


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for docker


.SH SEE ALSO
.PP
\fBdocker-attach(1)\fP, \fBdocker-buildx(1)\fP
