.nh
.TH "DOCKER" "1" "Jan 2020" "Docker Community" "Docker User Manuals"

.SH NAME
.PP
docker-buildx-dial-stdio - Proxy current stdio streams to builder instance


.SH SYNOPSIS
.PP
\fBdocker buildx dial-stdio\fP


.SH DESCRIPTION
.PP
Proxy current stdio streams to builder instance


.SH OPTIONS
.PP
\fB--platform\fP=""
	Target platform: this is used for node selection

.PP
\fB--progress\fP="quiet"
	Set type of progress output (auto, plain, tty).


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--builder\fP=""
	Override the configured builder instance


.SH SEE ALSO
.PP
\fBdocker-buildx(1)\fP
