.nh
.TH "DOCKER" "1" "Jan 2020" "Docker Community" "Docker User Manuals"

.SH NAME
docker-buildx-install - Install buildx as a 'docker builder' alias


.SH SYNOPSIS
\fBdocker buildx install\fP


.SH DESCRIPTION
Install buildx as a 'docker builder' alias


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--builder\fP=""
	Override the configured builder instance


.SH SEE ALSO
\fBdocker-buildx(1)\fP
