.nh
.TH "DOCKER" "1" "Jan 2020" "Docker Community" "Docker User Manuals"

.SH NAME
docker - A self-sufficient runtime for containers


.SH SYNOPSIS
\fBdocker [OPTIONS] COMMAND [ARG...]\fP


.SH DESCRIPTION
A self-sufficient runtime for containers


.SH OPTIONS
\fB-H\fP, \fB--host\fP="unix:///var/run/docker.sock"
	Daemon socket to connect to


.SH SEE ALSO
\fBdocker-attach(1)\fP, \fBdocker-buildx(1)\fP
