.nh
.TH "DOCKER" "1" "Jan 2020" "Docker Community" "Docker User Manuals"

.SH NAME
docker-buildx - Docker Buildx


.SH SYNOPSIS
\fBdocker buildx\fP


.SH DESCRIPTION
Extended build capabilities with BuildKit


.SH OPTIONS
\fB--builder\fP=""
	Override the configured builder instance


.SH SEE ALSO
\fBdocker(1)\fP, \fBdocker-buildx-build(1)\fP, \fBdocker-buildx-dial-stdio(1)\fP, \fBdocker-buildx-stop(1)\fP
